export const routePermissions: Record<string, { module: string; action: string }> = {
  "/": { module: "Dashboard", action: "view" },
  "/users/all": { module: "Users", action: "view" },
  "/users/:id": { module: "Users", action: "view" },
  "/agent/generate": { module: "AI Agent", action: "view" },
  "/employee/all": { module: "Employees", action: "view" },
  "/employee/:id": { module: "Employees", action: "view" },
  "/users/roles": { module: "Roles", action: "view" },
  "/users/departments": { module: "Departments", action: "view" },
  "/users/work-types": { module: "Work Types", action: "view" },
  "/category/list": { module: "Categories", action: "view" },
  "/sub/category": { module: "SubCategories", action: "view" },
  "/subscription": { module: "Subscription", action: "view" },
  "/job/list": { module: "Job Management", action: "view" },
  "/setup/media": { module: "Media Library", action: "view" },
  "/setup/general": { module: "General Settings", action: "view" },
  "/setup/business": { module: "Business Setup", action: "view" },
  "/profile": { module: "Profile Management", action: "view" },
  "/profile/edit": { module: "Profile Management", action: "update" },
  "/productions/plan": { module: "Productions", action: "view" },
  "/productions/work-orders": { module: "Productions", action: "view" },
  "/sales/summary": { module: "Sales Management", action: "view" },
  "/sales/ledger": { module: "Sales Management", action: "view" },
  "/crm/user-list": { module: "CRM", action: "view" },
  // blogs =============================================
  "/blog/list": { module: "Blog", action: "view" },
  "/blog/:id": { module: "Blog", action: "view" },
  "/blog/edit/:id": { module: "Blog", action: "view" },
  "/blog/create": { module: "Blog", action: "view" },
  "/blog/details/:id": { module: "Blog", action: "view" },
  "/contact/list": { module: "Contacts", action: "view" },
};
