export const routePermissions: Record<string, { module: string; action: string }> = {
  "/": { module: "Dashboard", action: "view" },
  "/employee/all": { module: "Employees", action: "view" },
  "/employee/:id": { module: "Employees", action: "view" },
  "/users/roles": { module: "Roles", action: "view" },
  "/users/departments": { module: "Departments", action: "view" },
  "/users/work-types": { module: "Work Types", action: "view" },
  "/category/list": { module: "Categories", action: "view" },
  "/sub/category": { module: "SubCategories", action: "view" },
  "/subscription": { module: "Subscription", action: "view" },
  "/job/list": { module: "Job Management", action: "view" },
  "/setup/media": { module: "Settings", action: "view" },
  "/setup/general": { module: "Settings", action: "view" },
  "/setup/business": { module: "Settings", action: "view" },
  "/profile": { module: "Profile", action: "view" },
  "/profile/edit": { module: "Profile", action: "update" },
  "/productions/plan": { module: "Productions", action: "view" },
  "/productions/work-orders": { module: "Productions", action: "view" },
  "/sales/summary": { module: "Sales Management", action: "view" },
  "/sales/ledger": { module: "Sales Management", action: "view" },
};
